name: Semgrep Django

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  schedule:
    - cron: '31 5 * * 3'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep:
    name: Django scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep:latest

    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run Semgrep default Django/Python rules
        run: |
          semgrep scan \
            --config auto \
            --config p/python \
            --config p/django \
            --sarif \
            --output semgrep-django.sarif \
            .

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-django.sarif
